version: "3.7"

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - my_caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - my_n8n_data:/home/node/.n8n
      - ${DATA_FOLDER}/local_files:/files

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: unless-stopped
    ports:
      - 6333:6333
    environment:
      - QDRANT_API_KEY=123
    volumes:
      - my_qdrant_storage:/qdrant/storage
      - ${DATA_FOLDER}/my_qdrant_config.yml:/qdrant/config/production.yaml

volumes:
  my_caddy_data:
    external: true
  my_n8n_data:
    external: true
  my_qdrant_storage:
    external: true
